export const pokemonColors = {
	normal: '#A8A77A',
	fire: '#EE8130',
	water: '#6390F0',
	electric: '#F7D02C',
	grass: '#7AC74C',
	ice: '#96D9D6',
	fighting: '#C22E28',
	poison: '#A33EA1',
	ground: '#E2BF65',
	flying: '#A98FF3',
	psychic: '#F95587',
	bug: '#A6B91A',
	rock: '#B6A136',
	ghost: '#735797',
	dragon: '#6F35FC',
	dark: '#705746',
	steel: '#B7B7CE',
	fairy: '#D685AD',
};

export const pokemonQuotes = [
	"I choose you!",
	"I’m not gonna stop, not ever!",
	"I’m gonna be the very best, like no one ever was!",
	"I’ll catch ‘em all!",
	"There’s no time like the present!",
	"I’m Misty, the Cerulean City Gym Leader!",
	"You’ll never beat me, Ash!",
	"You think you can win? You’re gonna be in for a surprise!",
	"Prepare for trouble! And make it double!",
	"To protect the world from devastation!",
	"Team Rocket's blasting off again!",
	"I’m Brock, the Pewter City Gym Leader.",
	"Rock-type Pokémon are the best!",
	"You’ll have to be strong to beat me!"
  ];